[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
hex = "0.4.3"
grpc = { workspace = true }
clap = { version = "4.5.7", features = ["cargo"] }
